language: python
python:
  - "2.7"
  - "3.5"

matrix:
  include:
    - env: LINT_CHECK
      install: pip install flake8
      script:
        - flake8
        - python -c "import extreme_classification"
