- kwargs:
    in_features: 1836
    out_features: 1390
  name: Linear
- kwargs:
    inplace: true
    negative_slope: 0.2
  name: LeakyReLU
- kwargs:
    in_features: 1390
    out_features: 945
  name: Linear
- kwargs:
    inplace: true
    negative_slope: 0.2
  name: LeakyReLU
- kwargs:
    in_features: 945
    out_features: 500
  name: Linear
- name: Sigmoid
