- kwargs:
    in_features: 100
    out_features: 678
  name: Linear
- kwargs:
    inplace: true
    negative_slope: 0.2
  name: LeakyReLU
- kwargs:
    in_features: 678
    out_features: 1257
  name: Linear
- kwargs:
    inplace: true
    negative_slope: 0.2
  name: LeakyReLU
- kwargs:
    in_features: 1257
    out_features: 1836
  name: Linear
- name: Sigmoid
