- kwargs:
    in_features: 500
    out_features: 300
  name: Linear
- kwargs:
    inplace: true
    negative_slope: 0.2
  name: LeakyReLU
- kwargs:
    in_features: 300
    out_features: 100
  name: Linear
- name: Sigmoid
