- kwargs:
    in_features: 500
    out_features: 366
  name: Linear
- kwargs:
    inplace: true
    negative_slope: 0.2
  name: LeakyReLU
- kwargs:
    in_features: 366
    out_features: 233
  name: Linear
- kwargs:
    inplace: true
    negative_slope: 0.2
  name: LeakyReLU
- kwargs:
    in_features: 233
    out_features: 100
  name: Linear
- name: Sigmoid
