- kwargs:
    in_features: 120
    out_features: 75
  name: Linear
- kwargs:
    inplace: true
    negative_slope: 0.2
  name: LeakyReLU
- kwargs:
    in_features: 75
    out_features: 30
  name: Linear
- name: Sigmoid
